[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/rfs"
  to = "https://frontside-software.typeform.com/to/h4jmH8qH"

[[redirects]]
  from = "/talk"
  to = "https://frontside-software.typeform.com/to/h4jmH8qH"

  
[[redirects]]
  from = "/rsvp"
  to = "https://hopin.com/events/backstage-users-unconference-mar-22"
  
[[redirects]]
  from = "/join"
  to = "https://frontside-software.typeform.com/to/Hwa01bCH"
