[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/rfs"
  to = "https://frontside-software.typeform.com/to/h4jmH8qH"

[[redirects]]
  from = "/talk"
  to = "https://frontside-software.typeform.com/to/h4jmH8qH"


[[redirects]]
  from = "/talkGot"
  to = "https://frontside-software.typeform.com/to/h4jmH8qH"
  
[[redirects]]
  from = "/rsvp"
  to = "  https://frontside-software.typeform.com/to/Tipri78x"
  